apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-pipeline
spec:
  template:
    spec:
      containers:
        - name: pipeline
          envFrom:
            - configMapRef:
                name: pipeline-config
            - secretRef:
                name: snowflake-credentials
