apiVersion: v1
kind: Service
metadata:
  name: enterprise-pipeline
  labels:
    app: enterprise-pipeline
spec:
  selector:
    app: enterprise-pipeline
  ports:
    - name: spark-ui
      port: 4040
      targetPort: 4040
